- hosts: local
  user: cloud
  sudo: true

  tasks:
    - name: apt-get update & upgrade
      apt:
        upgrade=full
        update_cache=yes
        cache_valid_time=3600

    - name: packages installed
      apt:
        pkg={{ item }}
        state=present
      with_items:
        - apache2
        - mysql-server
        - php5
        - libapache2-mod-php5
        - php5-mysql

    - name: apache running
      service:
        name=apache2
        state=running
        enabled=yes

    - name: apache site configuration
      copy:
        src=files/cw.apache2.conf
        dest=/etc/apache2/sites-available/default-cw.conf
        owner=root
        group=root
        mode=0644
      notify: enable apache site

    - name: deploy
      git:
        repo=https://github.com/aurelienmaury/cw-bundle-lamp.git
        dest=/var/www/cw
      
  handlers:
    - name: enable apache site
      shell: /usr/sbin/a2dissite 000-default && /usr/sbin/a2ensite default-cw
      notify: restart apache
      
    - name: restart apache
      service:
        name=apache2
        state=restarted